#!/bin/bash

# Prompt the user to enter the first number
echo "Enter the first number :"
read number1

# Prompt the user to enter the second number
echo "Enter the second number:"
read num2

# Add the two numbers
sum=$((num1 + num2))

# Print the result
echo "The sum of $num1 and $num2 is: $sum"

